force-app/main/default/objects/Campaign/fields/Cupom__c.field-meta.xml
<CustomField>
    <fullName>Cupom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cupom</label>
    <referenceTo>Cupom__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cupom__c/Cupom__c.object-meta.xml
<CustomObject>
    <label>Cupom</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Cupom Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cupom__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cupom__c/fields/Desconto__c.field-meta.xml
<CustomField>
    <fullName>Desconto__c</fullName>
    <label>Desconto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AttachCampaingsTest.cls
@isTest
private class AttachCampaingsTest {
   
    @TestSetup
    static void criarRegistros(){
        
      Cupom__c cp1 = new Cupom__c();
      cp1.Desconto__c = 0.20;
      cp1.Ativo__c = true;

      Cupom__c cp2 = new Cupom__c();
      cp2.Desconto__c = 0.10;
      cp2.Ativo__c = false;


      database.insert(new list<Cupom__c>{cp1, cp2});
    }

    @isTest
    static void recuperarCuponsComSucesso(){

        test.startTest();

          list<Cupom__c> lstCupons = AttachCampaings.getCupons();

        test.stopTest();

        System.assertEquals(1, lstCupons.size(), 'Não foram localizados cupons');
    }

    @isTest
    static void inserirCampanhasComSucesso(){
       

        list<Cupom__c> lstCupons = AttachCampaings.getCupons();

        Campaign cpm = new Campaign();
        cpm.Name = 'Campanha teste';
        cpm.IsActive = true;
        cpm.Status = 'Planned';
        cpm.Type = 'Advertisement';
        cpm.Cupom__c = lstCupons[0].Id;

        List<Campaign> lstcmp = new List<Campaign>{cpm};

        test.startTest();
           String statusOperacao = AttachCampaings.insertCampaings(lstcmp);
        test.stopTest();    

        System.assertEquals('Sucesso', statusOperacao, 'Campanha não foi criada com sucesso');
    }
}